### ISSUE TITLE
feature: support typescript

### ISSUE THREAD

**Issue by UltiRequiem** [UltiRequiem/react-run#2]
Options

1) Still using the browser to manage al js related, using something like https://github.com/harrysolovay/ts-browser

2) Integrate swc/similar to parse jsx+ts

**Comment by UltiRequiem** [comment]
(not yet) working example
```rust
use std::{path::Path, sync::Arc};
use swc::{self, config::Options};
use swc_common::{
    errors::{ColorConfig, Handler},
    SourceMap,
};

fn main() {
    let cm = Arc::<SourceMap>::default();

    let fm = cm
        .load_file(Path::new("foo.ts"))
        .expect("failed to load file");

    let handler = Arc::new(Handler::with_tty_emitter(
        ColorConfig::Auto,
        true,
        false,
        Some(cm.clone()),
    ));

    let c = swc::Compiler::new(cm.clone());

    let output = c
        .process_js_file(
            fm,
            &handler,
            &Options {
                ..Default::default()
            },
        )
        .expect("failed to process file");

    println!("{:#?}", output.code);
}
```

Cargo.toml
```toml
[package]
name = "swc_test"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_common = { version = "0.17.2", features = ["tty-emitter"] }
swc = "0.116.23"
```
